language: python

matrix:
  include:
    - python: 2.6
      sudo: required
      dist: trusty
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: "pypy"


# This disables sudo, but makes builds start much faster
# See http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
before_install: source ./ci/before_install.sh
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then source activate testenv; fi
  - pip install .
  - pip install -r dev-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == *'2.6'* ]]; then pip install tornado==4.2.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION != *'2.6'* ]]; then pip install tornado; fi
  - pip list
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != *'2.6'* ]]; then pip install flake8; else pip install flake8\<3; fi
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - python ci/install_coverage_subprocess_pth.py
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then source activate testenv; fi
  - COVERAGE_PROCESS_START="$TRAVIS_BUILD_DIR/.coveragerc" PYTHONPATH='.:tests' py.test -r s
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then source activate testenv; fi
  - coverage combine --append
  - codecov
